server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/travel_predict?useSSL=false&characterEncoding=UTF8&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 19990501
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: travel_predict


